require 'slack-ruby-bot'
require 'slack_swimmy/commands/FBot'
require 'slack_swimmy/commands/AmeBot'
require 'slack_swimmy/commands/TakaBot'
require 'slack_swimmy/commands/SYBot'
require 'slack_swimmy/app'
require 'slack_swimmy/commands/post_auto'